apiVersion: batch/v1
kind: Job
metadata:
  name: iperf3-client-template
  namespace: loadtest
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        job: iperf3-client
    spec:
      restartPolicy: Never
      containers:
      - name: iperf3-client
        image: networkstatic/iperf3:latest
        env:
        - name: TARGET
          value: iperf3-server
        - name: DURATION
          value: "30"
        command:
        - /bin/sh
        - -c
        - |
          iperf3 -c ${TARGET} -t ${DURATION} -J > /mnt/data/iperf_result.json || true
          cat /mnt/data/iperf_result.json
        volumeMounts:
        - name: results
          mountPath: /mnt/data
      volumes:
      - name: results
        persistentVolumeClaim:
          claimName: pvc-1g