# Template Job for Fortio client (instantiate with `kubectl create -f` after replacing TARGET/CONCURRENCY/DURATION)
apiVersion: batch/v1
kind: Job
metadata:
  name: fortio-client-template
  namespace: loadtest
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        job: fortio-client
    spec:
      restartPolicy: Never
      containers:
      - name: fortio-client
        image: fortio/fortio:latest
        env:
        - name: TARGET
          value: fortio-server
        - name: CONCURRENCY
          value: "4"
        - name: DURATION
          value: "30s"
        args:
          - "load"
          - "-c"
          - "$(CONCURRENCY)"
          - "-t"
          - "$(DURATION)"
          - "-qps"
          - "0"
          - "-json"
          - "/mnt/data/fortio_result.json"
          - "http://$(TARGET):8080/"
        volumeMounts:
        - name: results
          mountPath: /mnt/data
      volumes:
      - name: results
        persistentVolumeClaim:
          claimName: pvc-1g