apiVersion: svc.skycluster.io/v1alpha1
kind: XKube
metadata:
  name: xkube-1234
spec:
  applicationId: "app-1234"

  # Must be defined when deployment manifest is used
  # # Optional: service network CIDR (AWS-style)
  # serviceCidr: "10.200.0.0/20"

  # # Optional: node network CIDR (GCP-style)
  # nodeCidr: "10.210.0.0/20"

  # Pod CIDR definitions
  # podCidr:
  #   cidr: "10.100.0.0/16"
  #   public: "10.100.1.0/24"     # optional, AWS example
  #   private: "10.100.2.0/24"    # optional, AWS example

  # Node groups
  nodeGroups:
    - instanceTypes:
        - vcpus: "4"
          ram: 16GB
      outboundTraffic:
        totalDataTransfer: "10GB"
    - instanceTypes:
        - vcpus: "4"
          ram: 16GB
          gpu:
            model: L4
        - vcpus: "4"
          ram: 16GB
      outboundTraffic:
        totalDataTransfer: "10GB"
      publicAccess: false
      autoScaling:
        minSize: 2
        maxSize: 5

  # Principal performing control plane actions
  principal:
    type: "role"
    id: "arn:aws:iam::111122223333:role/SkyClusterControlPlane"

  # # Provider reference (must match Provider instance)
  # providerRef:
  #   kind: "Provider"
  #   name: "aws-provider"
  #   namespace: "skycluster-system"
