apiVersion: core.skycluster.io/v1alpha1
kind: SkyXRD
metadata:
  creationTimestamp: "2025-10-19T21:28:41Z"
  generateName: redis-app-policies-
  generation: 1
  name: redis-app-policies-5kxwm
  namespace: redis-app
  resourceVersion: "83704501"
  uid: e7a65615-d3bc-4116-b0a2-609d05aa61db
spec:
  approve: false
  dataflowPolicyRef:
    name: redis-app-policies
    resourceVersion: "83697259"
  deployPlan:
    components:
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: gateway
      providerRef:
        name: aws-us-east-1
        platform: aws
        region: us-east-1
        regionAlias: us-east
        type: cloud
        zone: us-east-1b
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: gateway
      providerRef:
        name: aws-us-west-1
        platform: aws
        region: us-west-1
        regionAlias: us-west
        type: cloud
        zone: us-west-1b
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: worker
      providerRef:
        name: aws-us-east-2
        platform: aws
        region: us-east-2
        regionAlias: us-east
        type: cloud
        zone: us-east-2b
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: backend
      providerRef:
        name: aws-us-east-2
        platform: aws
        region: us-east-2
        regionAlias: us-east
        type: cloud
        zone: us-east-2b
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: redis
      providerRef:
        name: aws-us-east-2
        platform: aws
        region: us-east-2
        regionAlias: us-east
        type: cloud
        zone: us-east-2b
    edges:
    - from:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: gateway
        providerRef:
          name: aws-us-east-1
          region: us-east-1
          regionAlias: us-east
          type: cloud
          zone: us-east-1b
      latency: "1.0"
      to:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: redis
        providerRef:
          name: aws-us-east-2
          region: us-east-2
          regionAlias: us-east
          type: cloud
          zone: us-east-2b
    - from:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: gateway
        providerRef:
          name: aws-us-west-1
          region: us-west-1
          regionAlias: us-west
          type: cloud
          zone: us-west-1b
      latency: "1.0"
      to:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: redis
        providerRef:
          name: aws-us-east-2
          region: us-east-2
          regionAlias: us-east
          type: cloud
          zone: us-east-2b
    - from:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: backend
        providerRef:
          name: aws-us-east-2
          region: us-east-2
          regionAlias: us-east
          type: cloud
          zone: us-east-2b
      latency: "1.0"
      to:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: redis
        providerRef:
          name: aws-us-east-2
          region: us-east-2
          regionAlias: us-east
          type: cloud
          zone: us-east-2b
    - from:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: worker
        providerRef:
          name: aws-us-east-2
          region: us-east-2
          regionAlias: us-east
          type: cloud
          zone: us-east-2b
      latency: "1.0"
      to:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: redis
        providerRef:
          name: aws-us-east-2
          region: us-east-2
          regionAlias: us-east
          type: cloud
          zone: us-east-2b
  deploymentPlanRef:
    name: redis-app-policies
    resourceVersion: "83697264"
status:
  conditions:
  - lastTransitionTime: "2025-10-19T21:37:44Z"
    message: SkyXRD reconciled successfully.
    reason: Reconciled
    status: "True"
    type: Ready
  manifests:
  - componentRef:
      apiVersion: skycluster.io/v1alpha1
      kind: XProvider
      name: aws-us-east-2
    manifest: |
      apiVersion: skycluster.io/v1alpha1
      kind: XProvider
      metadata:
          name: aws-us-east-2
      spec:
          applicationId: redis-app-policies-5kxwm
          externalNetwork: null
          gateway:
              flavor: ""
              volumeSize: 30
              volumeType: gp2
          providerRef:
              name: aws-us-east-2
              platform: aws
              region: us-east-2
              zones:
                  primary: us-east-2b
                  secondary: us-east-2a
          subnets:
              - cidr: 10.33.0.0/19
                type: public
                zone: us-east-2b
              - cidr: 10.33.32.0/19
                type: private
                zone: us-east-2b
          vpcCidr: 10.33.0.0/16
    providerRef:
      name: aws-us-east-2
      platform: aws
      region: us-east-2
      regionAlias: us-east
      type: cloud
      zone: us-east-2b
  - componentRef:
      apiVersion: skycluster.io/v1alpha1
      kind: XProvider
      name: aws-us-east-1
    manifest: |
      apiVersion: skycluster.io/v1alpha1
      kind: XProvider
      metadata:
          name: aws-us-east-1
      spec:
          applicationId: redis-app-policies-5kxwm
          externalNetwork: null
          gateway:
              flavor: ""
              volumeSize: 30
              volumeType: gp2
          providerRef:
              name: aws-us-east-1
              platform: aws
              region: us-east-1
              zones:
                  primary: us-east-1b
                  secondary: us-east-1a
          subnets:
              - cidr: 10.34.0.0/19
                type: public
                zone: us-east-1b
              - cidr: 10.34.32.0/19
                type: private
                zone: us-east-1b
          vpcCidr: 10.34.0.0/16
    providerRef:
      name: aws-us-east-1
      platform: aws
      region: us-east-1
      regionAlias: us-east
      type: cloud
      zone: us-east-1b
  - componentRef:
      apiVersion: skycluster.io/v1alpha1
      kind: XProvider
      name: aws-us-west-1
    manifest: |
      apiVersion: skycluster.io/v1alpha1
      kind: XProvider
      metadata:
          name: aws-us-west-1
      spec:
          applicationId: redis-app-policies-5kxwm
          externalNetwork: null
          gateway:
              flavor: ""
              volumeSize: 30
              volumeType: gp2
          providerRef:
              name: aws-us-west-1
              platform: aws
              region: us-west-1
              zones:
                  primary: us-west-1b
                  secondary: us-west-1c
          subnets:
              - cidr: 10.35.0.0/19
                type: public
                zone: us-west-1b
              - cidr: 10.35.32.0/19
                type: private
                zone: us-west-1b
          vpcCidr: 10.35.0.0/16
    providerRef:
      name: aws-us-west-1
      platform: aws
      region: us-west-1
      regionAlias: us-west
      type: cloud
      zone: us-west-1b
  - componentRef:
      apiVersion: skycluster.io/v1alpha1
      kind: XKube
      name: redis-app-policies-5kxwm
      namespace: redis-app
    manifest: |
      apiVersion: skycluster.io/v1alpha1
      kind: XKube
      metadata:
          name: redis-app-policies-5kxwm
          namespace: redis-app
      spec:
          applicationId: redis-app-policies-5kxwm
          nodeGroups:
              - autoScaling:
                  enabled: false
                  maxSize: 2
                  minSize: 1
                instanceType: 4vCPU-8GB
                publicAccess: true
          podCidr:
              cidr: 10.33.128.0/17
              private: 10.33.192.0/18
              public: 10.33.128.0/18
          principal:
              id: arn:aws:iam::885707601199:root
              type: servicePrincipal
          providerRef:
              name: aws-us-west-1
              platform: aws
              region: us-west-1
              zones:
                  primary: us-west-1b
                  secondary: us-west-1c
          serviceCidr: 10.255.0.0/16
    providerRef:
      name: aws-us-west-1
      platform: aws
      region: us-west-1
      regionAlias: us-west
      type: cloud
      zone: us-west-1b
  - componentRef:
      apiVersion: skycluster.io/v1alpha1
      kind: XKube
      name: redis-app-policies-5kxwm
      namespace: redis-app
    manifest: |
      apiVersion: skycluster.io/v1alpha1
      kind: XKube
      metadata:
          name: redis-app-policies-5kxwm
          namespace: redis-app
      spec:
          applicationId: redis-app-policies-5kxwm
          nodeGroups:
              - autoScaling:
                  enabled: false
                  maxSize: 2
                  minSize: 1
                instanceType: 4vCPU-8GB
                publicAccess: true
          podCidr:
              cidr: 10.34.128.0/17
              private: 10.34.192.0/18
              public: 10.34.128.0/18
          principal:
              id: arn:aws:iam::885707601199:root
              type: servicePrincipal
          providerRef:
              name: aws-us-east-2
              platform: aws
              region: us-east-2
              zones:
                  primary: us-east-2a
                  secondary: us-east-2b
          serviceCidr: 10.254.0.0/16
    providerRef:
      name: aws-us-east-2
      platform: aws
      region: us-east-2
      regionAlias: us-east
      type: cloud
      zone: us-east-2a
  - componentRef:
      apiVersion: skycluster.io/v1alpha1
      kind: XKube
      name: redis-app-policies-5kxwm
      namespace: redis-app
    manifest: |
      apiVersion: skycluster.io/v1alpha1
      kind: XKube
      metadata:
          name: redis-app-policies-5kxwm
          namespace: redis-app
      spec:
          applicationId: redis-app-policies-5kxwm
          nodeGroups:
              - autoScaling:
                  enabled: false
                  maxSize: 2
                  minSize: 1
                instanceType: 4vCPU-8GB
                publicAccess: true
          podCidr:
              cidr: 10.35.128.0/17
              private: 10.35.192.0/18
              public: 10.35.128.0/18
          principal:
              id: arn:aws:iam::885707601199:root
              type: servicePrincipal
          providerRef:
              name: aws-us-east-1
              platform: aws
              region: us-east-1
              zones:
                  primary: us-east-1a
                  secondary: us-east-1b
          serviceCidr: 10.253.0.0/16
    providerRef:
      name: aws-us-east-1
      platform: aws
      region: us-east-1
      regionAlias: us-east
      type: cloud
      zone: us-east-1a
  ready: false
  synced: false
