apiVersion: core.skycluster.io/v1alpha1
kind: SkyXRD
metadata:
  creationTimestamp: "2025-10-20T16:39:25Z"
  generateName: redis-app-policies-
  generation: 1
  name: redis-app-policies-w4gjf
  namespace: redis-app
  resourceVersion: "355395"
  uid: ead34e0d-9946-4429-b3ca-d2a5044bd5da
spec:
  approve: false
  dataflowPolicyRef:
    name: redis-app-policies
    resourceVersion: "67571"
  deployPlan:
    components:
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: gateway
      providerRef:
        name: gcp-us-central1
        platform: gcp
        region: us-central1
        regionAlias: us-east
        type: cloud
        zone: us-central1-c
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: worker
      providerRef:
        name: gcp-us-central1
        platform: gcp
        region: us-central1
        regionAlias: us-east
        type: cloud
        zone: us-central1-c
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: backend
      providerRef:
        name: aws-us-west-2
        platform: aws
        region: us-west-2
        regionAlias: us-west
        type: cloud
        zone: us-west-2b
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: redis
      providerRef:
        name: gcp-us-central1
        platform: gcp
        region: us-central1
        regionAlias: us-east
        type: cloud
        zone: us-central1-c
    edges:
    - from:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: gateway
        providerRef:
          name: gcp-us-central1
          region: us-central1
          regionAlias: us-east
          type: cloud
          zone: us-central1-c
      latency: "1.0"
      to:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: redis
        providerRef:
          name: gcp-us-central1
          region: us-central1
          regionAlias: us-east
          type: cloud
          zone: us-central1-c
    - from:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: backend
        providerRef:
          name: aws-us-west-2
          region: us-west-2
          regionAlias: us-west
          type: cloud
          zone: us-west-2b
      latency: "1.0"
      to:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: redis
        providerRef:
          name: gcp-us-central1
          region: us-central1
          regionAlias: us-east
          type: cloud
          zone: us-central1-c
    - from:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: worker
        providerRef:
          name: gcp-us-central1
          region: us-central1
          regionAlias: us-east
          type: cloud
          zone: us-central1-c
      latency: "1.0"
      to:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: redis
        providerRef:
          name: gcp-us-central1
          region: us-central1
          regionAlias: us-east
          type: cloud
          zone: us-central1-c
  deploymentPlanRef:
    name: redis-app-policies
    resourceVersion: "67574"
status:
  conditions:
  - lastTransitionTime: "2025-10-20T16:39:25Z"
    message: SkyXRD reconciled successfully.
    reason: Reconciled
    status: "True"
    type: Ready
  manifests:
  - componentRef:
      apiVersion: skycluster.io/v1alpha1
      kind: XProvider
      name: xp-gcp-us-centr-c7h3w
    manifest: |
      apiVersion: skycluster.io/v1alpha1
      kind: XProvider
      metadata:
          name: xp-gcp-us-centr-c7h3w
      spec:
          applicationId: redis-app-policies-w4gjf
          externalNetwork: null
          gateway:
              flavor: 2vCPU-8GB
          providerRef:
              platform: gcp
              region: us-central1
              zones:
                  primary: us-central1-b
                  secondary: us-central1-c
          subnets:
              - cidr: 10.29.0.0/18
                zone: us-central1-c
          vpcCidr: 10.29.0.0/16
    providerRef:
      name: gcp-us-central1
      platform: gcp
      region: us-central1
      regionAlias: us-east
      type: cloud
      zone: us-central1-c
  - componentRef:
      apiVersion: skycluster.io/v1alpha1
      kind: XProvider
      name: xp-aws-us-west--1wegm
    manifest: |
      apiVersion: skycluster.io/v1alpha1
      kind: XProvider
      metadata:
          name: xp-aws-us-west--1wegm
      spec:
          applicationId: redis-app-policies-w4gjf
          externalNetwork: null
          gateway:
              flavor: 4vCPU-16GB
              volumeSize: 30
              volumeType: gp2
          providerRef:
              platform: aws
              region: us-west-2
              zones:
                  primary: us-west-2a
                  secondary: us-west-2b
          subnets:
              - cidr: 10.76.0.0/19
                type: public
                zone: us-west-2b
              - cidr: 10.76.32.0/19
                type: private
                zone: us-west-2b
          vpcCidr: 10.76.0.0/16
    providerRef:
      name: aws-us-west-2
      platform: aws
      region: us-west-2
      regionAlias: us-west
      type: cloud
      zone: us-west-2b
  - componentRef:
      apiVersion: skycluster.io/v1alpha1
      kind: XKube
      name: xk-gcp-us-centr-2q1pc
    manifest: |
      apiVersion: skycluster.io/v1alpha1
      kind: XKube
      metadata:
          name: xk-gcp-us-centr-2q1pc
      spec:
          applicationId: redis-app-policies-w4gjf
          nodeCidr: 10.29.128.0/17
          nodeGroups:
              - autoScaling:
                  enabled: true
                  maxSize: 3
                  minSize: 1
                instanceType: 2vCPU-4GB
                nodeCount: 2
                publicAccess: false
          podCidr:
              cidr: 172.29.0.0/16
          principal: {}
          providerRef:
              platform: gcp
              region: us-central1
              zones:
                  primary: us-central1-b
          serviceCidr: ""
    providerRef:
      name: gcp-us-central1
      platform: gcp
      region: us-central1
      regionAlias: us-east
      type: cloud
      zone: us-central1-b
  - componentRef:
      apiVersion: skycluster.io/v1alpha1
      kind: XKube
      name: xk-aws-us-west--ksghn
    manifest: |
      apiVersion: skycluster.io/v1alpha1
      kind: XKube
      metadata:
          name: xk-aws-us-west--ksghn
      spec:
          applicationId: redis-app-policies-w4gjf
          nodeCidr: ""
          nodeGroups:
              - autoScaling:
                  enabled: false
                  maxSize: 2
                  minSize: 1
                instanceType: 4vCPU-8GB
                publicAccess: true
              - instanceType: 2vCPU-1GB
                publicAccess: false
              - instanceType: 2vCPU-2GB
                publicAccess: false
              - instanceType: 2vCPU-4GB
                publicAccess: false
              - instanceType: 2vCPU-8GB
                publicAccess: false
              - instanceType: 4vCPU-16GB
                publicAccess: false
          podCidr:
              cidr: 10.76.128.0/17
              private: 10.76.192.0/18
              public: 10.76.128.0/18
          principal:
              id: arn:aws:iam::885707601199:root
              type: servicePrincipal
          providerRef:
              platform: aws
              region: us-west-2
              zones:
                  primary: us-west-2a
                  secondary: us-west-2b
          serviceCidr: 10.212.0.0/16
    providerRef:
      name: aws-us-west-2
      platform: aws
      region: us-west-2
      regionAlias: us-west
      type: cloud
      zone: us-west-2a
  - componentRef:
      apiVersion: skycluster.io/v1alpha1
      kind: XKubeMesh
      name: xkmesh-redis-ap-s4usz
    manifest: |
      apiVersion: skycluster.io/v1alpha1
      kind: XKubeMesh
      metadata:
          name: xkmesh-redis-ap-s4usz
      spec:
          clusterNames:
              - xk-gcp-us-centr-2q1pc
              - xk-aws-us-west--ksghn
          localCluster:
              podCidr: 10.0.0.0/19
              serviceCidr: 10.0.32.0/19
    providerRef: {}
  ready: false
  synced: false
