apiVersion: core.skycluster.io/v1alpha1
kind: SkyXRD
metadata:
  creationTimestamp: "2025-10-22T07:05:42Z"
  generateName: redis-app-policies-
  generation: 1
  name: redis-app-policies-qx9mr
  namespace: redis-app
  resourceVersion: "2161355"
  uid: f3392b26-38bc-4114-bbc6-793d53a71b70
spec:
  approve: false
  dataflowPolicyRef:
    name: redis-app-policies
    resourceVersion: "1863225"
  deployPlan:
    components:
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: gateway
      providerRef:
        name: aws-us-east-1
        platform: aws
        region: us-east-1
        regionAlias: us-east
        type: cloud
        zone: us-east-1b
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: worker
      providerRef:
        name: aws-us-west-1
        platform: aws
        region: us-west-1
        regionAlias: us-west
        type: cloud
        zone: us-west-1c
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: backend
      providerRef:
        name: aws-us-west-1
        platform: aws
        region: us-west-1
        regionAlias: us-west
        type: cloud
        zone: us-west-1c
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: redis
      providerRef:
        name: aws-us-west-1
        platform: aws
        region: us-west-1
        regionAlias: us-west
        type: cloud
        zone: us-west-1c
    edges:
    - from:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: gateway
        providerRef:
          name: aws-us-east-1
          region: us-east-1
          regionAlias: us-east
          type: cloud
          zone: us-east-1b
      latency: "1.0"
      to:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: redis
        providerRef:
          name: aws-us-west-1
          region: us-west-1
          regionAlias: us-west
          type: cloud
          zone: us-west-1c
    - from:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: backend
        providerRef:
          name: aws-us-west-1
          region: us-west-1
          regionAlias: us-west
          type: cloud
          zone: us-west-1c
      latency: "1.0"
      to:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: redis
        providerRef:
          name: aws-us-west-1
          region: us-west-1
          regionAlias: us-west
          type: cloud
          zone: us-west-1c
    - from:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: worker
        providerRef:
          name: aws-us-west-1
          region: us-west-1
          regionAlias: us-west
          type: cloud
          zone: us-west-1c
      latency: "1.0"
      to:
        componentRef:
          apiVersion: apps/v1
          kind: Deployment
          name: redis
        providerRef:
          name: aws-us-west-1
          region: us-west-1
          regionAlias: us-west
          type: cloud
          zone: us-west-1c
  deploymentPlanRef:
    name: redis-app-policies
    resourceVersion: "1863228"
status:
  manifests:
  - componentRef:
      apiVersion: skycluster.io/v1alpha1
      kind: XProvider
      name: xp-aws-us-east--wa9kb
    manifest: |
      apiVersion: skycluster.io/v1alpha1
      kind: XProvider
      metadata:
          name: xp-aws-us-east--wa9kb
      spec:
          applicationId: redis-app-policies-qx9mr
          externalNetwork: null
          gateway:
              flavor: 4vCPU-16GB
              volumeSize: 30
              volumeType: gp2
          providerRef:
              platform: aws
              region: us-east-1
              zones:
                  primary: us-east-1a
                  secondary: us-east-1b
          subnets:
              - cidr: 10.89.0.0/19
                type: public
                zone: us-east-1b
              - cidr: 10.89.32.0/19
                type: private
                zone: us-east-1b
          vpcCidr: 10.89.0.0/16
    providerRef:
      name: aws-us-east-1
      platform: aws
      region: us-east-1
      regionAlias: us-east
      type: cloud
      zone: us-east-1b
  - componentRef:
      apiVersion: skycluster.io/v1alpha1
      kind: XProvider
      name: xp-aws-us-west--1wegm
    manifest: |
      apiVersion: skycluster.io/v1alpha1
      kind: XProvider
      metadata:
          name: xp-aws-us-west--1wegm
      spec:
          applicationId: redis-app-policies-qx9mr
          externalNetwork: null
          gateway:
              flavor: 4vCPU-16GB
              volumeSize: 30
              volumeType: gp2
          providerRef:
              platform: aws
              region: us-west-1
              zones:
                  primary: us-west-1b
                  secondary: us-west-1c
          subnets:
              - cidr: 10.70.0.0/19
                type: public
                zone: us-west-1c
              - cidr: 10.70.32.0/19
                type: private
                zone: us-west-1c
          vpcCidr: 10.70.0.0/16
    providerRef:
      name: aws-us-west-1
      platform: aws
      region: us-west-1
      regionAlias: us-west
      type: cloud
      zone: us-west-1c
  - componentRef:
      apiVersion: skycluster.io/v1alpha1
      kind: XKube
      name: xk-aws-us-east--evzal
    manifest: |
      apiVersion: skycluster.io/v1alpha1
      kind: XKube
      metadata:
          name: xk-aws-us-east--evzal
      spec:
          applicationId: redis-app-policies-qx9mr
          nodeCidr: ""
          nodeGroups:
              - autoScaling:
                  enabled: false
                  maxSize: 2
                  minSize: 1
                instanceTypes:
                  - 2vCPU-4GB
                  - 4vCPU-8GB
                  - 8vCPU-32GB
                nodeCount: 2
                publicAccess: true
              - instanceTypes:
                  - 16vCPU-256GB-1xH100-80GB
                publicAccess: false
              - instanceTypes:
                  - 2vCPU-1GB
                publicAccess: false
              - instanceTypes:
                  - 2vCPU-2GB
                publicAccess: false
              - instanceTypes:
                  - 2vCPU-4GB
                publicAccess: false
              - instanceTypes:
                  - 2vCPU-8GB
                publicAccess: false
          podCidr:
              cidr: 10.89.128.0/17
              private: 10.89.192.0/18
              public: 10.89.128.0/18
          principal:
              id: arn:aws:iam::885707601199:root
              type: servicePrincipal
          providerRef:
              platform: aws
              region: us-east-1
              zones:
                  primary: us-east-1a
                  secondary: us-east-1b
          serviceCidr: 10.199.0.0/16
    providerRef:
      name: aws-us-east-1
      platform: aws
      region: us-east-1
      regionAlias: us-east
      type: cloud
      zone: us-east-1a
  - componentRef:
      apiVersion: skycluster.io/v1alpha1
      kind: XKube
      name: xk-aws-us-west--ksghn
    manifest: |
      apiVersion: skycluster.io/v1alpha1
      kind: XKube
      metadata:
          name: xk-aws-us-west--ksghn
      spec:
          applicationId: redis-app-policies-qx9mr
          nodeCidr: ""
          nodeGroups:
              - autoScaling:
                  enabled: false
                  maxSize: 2
                  minSize: 1
                instanceTypes:
                  - 2vCPU-4GB
                  - 4vCPU-8GB
                  - 8vCPU-32GB
                nodeCount: 2
                publicAccess: true
              - instanceTypes:
                  - 2vCPU-1GB
                publicAccess: false
              - instanceTypes:
                  - 2vCPU-2GB
                publicAccess: false
              - instanceTypes:
                  - 2vCPU-4GB
                publicAccess: false
              - instanceTypes:
                  - 2vCPU-8GB
                publicAccess: false
              - instanceTypes:
                  - 4vCPU-16GB
                publicAccess: false
          podCidr:
              cidr: 10.70.128.0/17
              private: 10.70.192.0/18
              public: 10.70.128.0/18
          principal:
              id: arn:aws:iam::885707601199:root
              type: servicePrincipal
          providerRef:
              platform: aws
              region: us-west-1
              zones:
                  primary: us-west-1b
                  secondary: us-west-1c
          serviceCidr: 10.218.0.0/16
    providerRef:
      name: aws-us-west-1
      platform: aws
      region: us-west-1
      regionAlias: us-west
      type: cloud
      zone: us-west-1b
  - componentRef:
      apiVersion: skycluster.io/v1alpha1
      kind: XKubeMesh
      name: xkmesh-redis-ap-s4usz
    manifest: |
      apiVersion: skycluster.io/v1alpha1
      kind: XKubeMesh
      metadata:
          name: xkmesh-redis-ap-s4usz
      spec:
          clusterNames:
              - xk-aws-us-east--evzal
              - xk-aws-us-west--ksghn
          localCluster:
              podCidr: 10.0.0.0/19
              serviceCidr: 10.0.32.0/19
    providerRef: {}
  ready: false
  synced: false
