apiVersion: policy.skycluster.io/v1alpha1
kind: DataflowPolicy
metadata:
  name: redis-app-policies
  namespace: redis-app
spec:
  dataDependencies:
    - from:
        apiVersion: apps/v1
        kind: Deployment
        name: gateway
      to:
        apiVersion: apps/v1
        kind: Deployment
        name: redis
      latency: 500ms
      totalDataTransfer: 0.5GB
      averageDataRate: 0.01GB/s
    - from:
        apiVersion: apps/v1
        kind: Deployment
        name: backend
      to:
        apiVersion: apps/v1
        kind: Deployment
        name: redis
      latency: 500ms
      totalDataTransfer: 0.5GB
      averageDataRate: 0.01GB/s
    - from:
        apiVersion: apps/v1
        kind: Deployment
        name: worker
      to:
        apiVersion: apps/v1
        kind: Deployment
        name: redis
      latency: 500ms
      totalDataTransfer: 0.5GB
      averageDataRate: 0.01GB/s
---
apiVersion: policy.skycluster.io/v1alpha1
kind: DeploymentPolicy
metadata:
  name: redis-app-policies
  namespace: redis-app
spec:
  deploymentPolicies:
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: gateway
      virtualServiceConstraint:
      - anyOf:
        - name: EKS
          kind: ManagedKubernetes
      performanceConstraint:
        responseTime: 100ms
      locationConstraint:
        permitted:
          - platform: aws
        required: 
          - anyOf:
            - region: us-east-1
          - anyOf:
            - region: us-west-1
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: worker
      virtualServiceConstraint:
      - anyOf:
        - name: EKS
          kind: ManagedKubernetes
      performanceConstraint:
        responseTime: 100ms
      locationConstraint:
        permitted:
          - regionAlias: us-east
            platform: aws
          - regionAlias: toronto
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: backend # name must uniquely identify the component
      virtualServiceConstraint:
      - anyOf:
        - name: EKS
          kind: ManagedKubernetes
          # Other fields
          # apiVersion: <apiVersion>
          # count: <count>
      performanceConstraint:
        responseTime: 100ms
      locationConstraint:
        permitted:
          - regionAlias: us-east
            platform: aws
          - regionAlias: toronto
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: redis
      virtualServiceConstraint:
      - anyOf:
        - name: EKS
          kind: ManagedKubernetes
      performanceConstraint:
        responseTime: 100ms
      locationConstraint:
        permitted:
          - regionAlias: us-east
            platform: aws
---