apiVersion: policy.skycluster.io/v1alpha1
kind: DataflowPolicy
metadata:
  name: redis-pipeline-policies
  namespace: micro-pipeline
  labels:
    skycluster.io/app-id: testcase1
spec:
  dataDependencies:
    - from:
        apiVersion: apps/v1
        kind: Deployment
        name: producer
      to:
        apiVersion: apps/v1
        kind: Deployment
        name: processor
      latency: 500ms
      totalDataTransfer: 0.5GB
      averageDataRate: 0.01GB/s
    - from:
        apiVersion: apps/v1
        kind: Deployment
        name: processor
      to:
        apiVersion: apps/v1
        kind: Deployment
        name: aggregator
      latency: 500ms
      totalDataTransfer: 0.5GB
      averageDataRate: 0.01GB/s
    - from:
        apiVersion: apps/v1
        kind: Deployment
        name: producer
      to:
        apiVersion: apps/v1
        kind: Deployment
        name: redis
      latency: 500ms
      totalDataTransfer: 0.5GB
      averageDataRate: 0.01GB/s
    - from:
        apiVersion: apps/v1
        kind: Deployment
        name: processor
      to:
        apiVersion: apps/v1
        kind: Deployment
        name: redis
      latency: 500ms
      totalDataTransfer: 0.5GB
      averageDataRate: 0.01GB/s
    - from:
        apiVersion: apps/v1
        kind: Deployment
        name: aggregator
      to:
        apiVersion: apps/v1
        kind: Deployment
        name: redis
      latency: 500ms
      totalDataTransfer: 0.5GB
      averageDataRate: 0.01GB/s
---
apiVersion: policy.skycluster.io/v1alpha1
kind: DeploymentPolicy
metadata:
  name: redis-pipeline-policies
  namespace: micro-pipeline
  labels:
    skycluster.io/app-id: testcase1
spec:
  # The execution environment can be either Kubernetes or VirtualMachine
  # when it is Kubernetes, the controller will attempt to provision Kubernetes
  # clusters (managed or self-managed) to deploy the application components.
  # when it is VirtualMachine, the controller will attempt to provision VMs
  # to deploy the application components. 
  executionEnvironment: Kubernetes # Kubernetes | VirtualMachine
  deploymentPolicies:
    # Depending on the execution environment, the componentRef kind
    # can be Deployment (for Kubernetes) or inline Docker container spec (for VM).
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment # Deployment | DockerContainer
        name: producer
        spec: |
          # inline spec can go here if needed
      virtualServiceConstraint:
      # Virtual service constraints specify the required services
      # for hosting and running this component. 
      # Supported types: ComputeProfile (for VMs and underlying hosts in Kubernetes (node groups))
      # This could be extended to support multiple virtual service types
      - anyOf:
        - kind: ComputeProfile
        # must specify the ComputeProfile with json/yaml spec.
          spec: |
            {
              "vcpu": 2,
              "ram": 4
            }
      performanceConstraint:
        responseTime: 100ms
      locationConstraint:
        permitted:
          - platform: aws
          - platform: gcp
        required:
          - anyOf:
            - region: us-east-1
          - anyOf:
            - region: us-east1
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: processor
      virtualServiceConstraint:
      - anyOf:
        - name: ManagedKubernetes
      performanceConstraint:
        responseTime: 100ms
      locationConstraint:
        permitted:
          - platform: aws
          - platform: gcp
        required:
          - anyOf:
            - region: us-east-1
          - anyOf:
            - region: us-east1
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: aggregator
      virtualServiceConstraint:
      - anyOf:
        - name: ManagedKubernetes
      performanceConstraint:
        responseTime: 100ms
      locationConstraint:
        permitted:
          - platform: aws
          - platform: gcp
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: redis
      virtualServiceConstraint:
      - anyOf:
        - name: ManagedKubernetes
      performanceConstraint:
        responseTime: 100ms
      locationConstraint:
        permitted:
          - platform: aws
        required:
          - anyOf:
            - region: us-east-1
---