apiVersion: policy.skycluster.io/v1alpha1
kind: DataflowPolicy
metadata:
  name: loadtest-policies
  namespace: loadtest
  labels:
    skycluster.io/app-id: loadtest
    skycluster.io/app-scope: distributed
spec:
  dataDependencies: 
    - from:
        apiVersion: apps/v1
        kind: Deployment
        name: load-generator
      to:
        # There must be a service for data-sink deployment
        apiVersion: apps/v1
        kind: Deployment
        name: data-sink
      latency: 500ms
      totalDataTransfer: 0.5GB
      averageDataRate: 0.01GB/s
---
apiVersion: policy.skycluster.io/v1alpha1
kind: DeploymentPolicy
metadata:
  name: loadtest-policies
  namespace: loadtest
  labels:
    skycluster.io/app-id: loadtest
    skycluster.io/app-scope: distributed
spec:
  deploymentPolicies:
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: load-generator
      virtualServiceConstraint:
      - anyOf:
        - name: ManagedKubernetes
      performanceConstraint:
        responseTime: 100ms
      locationConstraint:
        permitted:
          - platform: aws
          - platform: gcp
        required:
          - anyOf:
            - region: us-east-1
          - anyOf:
            - region: us-east1
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: data-sink
      virtualServiceConstraint:
      - anyOf:
        - name: ManagedKubernetes
      performanceConstraint:
        responseTime: 100ms
      locationConstraint:
        permitted:
          - platform: aws
          - platform: gcp
        required:
          - anyOf:
            - region: us-east-1
          - anyOf:
            - region: us-east1
---