apiVersion: batch/v1
kind: Job
metadata:
  name: fortio-client-template
  namespace: loadtest
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        job: fortio-client
    spec:
      containers:
      - args:
        - load
        - -c
        - $(CONCURRENCY)
        - -t
        - $(DURATION)
        - -qps
        - '0'
        - -json
        - /mnt/data/fortio_result.json
        - http://$(TARGET):8080/
        env:
        - name: TARGET
          value: a7539eda8f1724befb3e21c123acb3e6-1295078554.us-east-1.elb.amazonaws.com
        - name: CONCURRENCY
          value: '4'
        - name: DURATION
          value: 30s
        image: fortio/fortio:latest
        name: fortio-client
        volumeMounts:
        - mountPath: /mnt/data
          name: results
      restartPolicy: Never
      volumes:
      - name: results
        persistentVolumeClaim:
          claimName: pvc-1g
---
apiVersion: batch/v1
kind: Job
metadata:
  name: iperf3-client-template
  namespace: loadtest
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        job: iperf3-client
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - 'iperf3 -c ${TARGET} -t ${DURATION} -J > /mnt/data/iperf_result.json ||
          true

          cat /mnt/data/iperf_result.json

          '
        env:
        - name: TARGET
          value: ab9ae01336c0e4acc861e533b2de070c-1901118216.us-east-1.elb.amazonaws.com
        - name: DURATION
          value: '30'
        image: networkstatic/iperf3:latest
        name: iperf3-client
        volumeMounts:
        - mountPath: /mnt/data
          name: results
      restartPolicy: Never
      volumes:
      - name: results
        persistentVolumeClaim:
          claimName: pvc-1g
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1g
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1g
  namespace: loadtest
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
