//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomMetric) DeepCopyInto(out *CustomMetric) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomMetric.
func (in *CustomMetric) DeepCopy() *CustomMetric {
	if in == nil {
		return nil
	}
	out := new(CustomMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataDapendency) DeepCopyInto(out *DataDapendency) {
	*out = *in
	out.From = in.From
	out.To = in.To
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataDapendency.
func (in *DataDapendency) DeepCopy() *DataDapendency {
	if in == nil {
		return nil
	}
	out := new(DataDapendency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataflowPolicy) DeepCopyInto(out *DataflowPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataflowPolicy.
func (in *DataflowPolicy) DeepCopy() *DataflowPolicy {
	if in == nil {
		return nil
	}
	out := new(DataflowPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataflowPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataflowPolicyList) DeepCopyInto(out *DataflowPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataflowPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataflowPolicyList.
func (in *DataflowPolicyList) DeepCopy() *DataflowPolicyList {
	if in == nil {
		return nil
	}
	out := new(DataflowPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataflowPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataflowPolicySpec) DeepCopyInto(out *DataflowPolicySpec) {
	*out = *in
	if in.DataDependencies != nil {
		in, out := &in.DataDependencies, &out.DataDependencies
		*out = make([]DataDapendency, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataflowPolicySpec.
func (in *DataflowPolicySpec) DeepCopy() *DataflowPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DataflowPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataflowPolicyStatus) DeepCopyInto(out *DataflowPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataflowPolicyStatus.
func (in *DataflowPolicyStatus) DeepCopy() *DataflowPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DataflowPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentPolicy) DeepCopyInto(out *DeploymentPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentPolicy.
func (in *DeploymentPolicy) DeepCopy() *DeploymentPolicy {
	if in == nil {
		return nil
	}
	out := new(DeploymentPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentPolicyItem) DeepCopyInto(out *DeploymentPolicyItem) {
	*out = *in
	out.ComponentRef = in.ComponentRef
	in.PerformanceConstraint.DeepCopyInto(&out.PerformanceConstraint)
	in.LocationConstraint.DeepCopyInto(&out.LocationConstraint)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentPolicyItem.
func (in *DeploymentPolicyItem) DeepCopy() *DeploymentPolicyItem {
	if in == nil {
		return nil
	}
	out := new(DeploymentPolicyItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentPolicyList) DeepCopyInto(out *DeploymentPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeploymentPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentPolicyList.
func (in *DeploymentPolicyList) DeepCopy() *DeploymentPolicyList {
	if in == nil {
		return nil
	}
	out := new(DeploymentPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentPolicySpec) DeepCopyInto(out *DeploymentPolicySpec) {
	*out = *in
	if in.DeploymentPolicies != nil {
		in, out := &in.DeploymentPolicies, &out.DeploymentPolicies
		*out = make([]DeploymentPolicyItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentPolicySpec.
func (in *DeploymentPolicySpec) DeepCopy() *DeploymentPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentPolicyStatus) DeepCopyInto(out *DeploymentPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentPolicyStatus.
func (in *DeploymentPolicyStatus) DeepCopy() *DeploymentPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DeploymentPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocationConstraint) DeepCopyInto(out *LocationConstraint) {
	*out = *in
	in.Permitted.DeepCopyInto(&out.Permitted)
	in.Required.DeepCopyInto(&out.Required)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocationConstraint.
func (in *LocationConstraint) DeepCopy() *LocationConstraint {
	if in == nil {
		return nil
	}
	out := new(LocationConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceConstraint) DeepCopyInto(out *PerformanceConstraint) {
	*out = *in
	if in.CustomMetrics != nil {
		in, out := &in.CustomMetrics, &out.CustomMetrics
		*out = make([]CustomMetric, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceConstraint.
func (in *PerformanceConstraint) DeepCopy() *PerformanceConstraint {
	if in == nil {
		return nil
	}
	out := new(PerformanceConstraint)
	in.DeepCopyInto(out)
	return out
}
