apiVersion: policy.skycluster.io/v1alpha1
kind: DataflowPolicy
metadata:
  name: echo-app-policies
  namespace: echo-app
  labels:
    skycluster.io/app-id: echo-app
    skycluster.io/app-scope: distributed
spec:
  dataDependencies:
    - from:
        apiVersion: apps/v1
        kind: Deployment
        name: netshoot-app
      to:
        apiVersion: apps/v1
        kind: Deployment
        name: echo-app
      latency: 500ms
      totalDataTransfer: 0.5GB
      averageDataRate: 0.01GB/s
---
apiVersion: policy.skycluster.io/v1alpha1
kind: DeploymentPolicy
metadata:
  name: echo-app-policies
  namespace: echo-app
  labels:
    skycluster.io/app-id: echo-app
    skycluster.io/app-scope: distributed
spec:
  deploymentPolicies:
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: netshoot-app
      virtualServiceConstraint:
      - anyOf:
        - name: ManagedKubernetes
      performanceConstraint:
        responseTime: 100ms
      locationConstraint:
        permitted:
          - platform: aws
        required:
          - anyOf:
            - region: us-east-1
          - anyOf:
            - region: us-west-1
    - componentRef:
        apiVersion: apps/v1
        kind: Deployment
        name: echo-app
      virtualServiceConstraint:
      - anyOf:
        - name: ManagedKubernetes
      performanceConstraint:
        responseTime: 100ms
      locationConstraint:
        permitted:
          - platform: aws
        required:
          - anyOf:
            - region: us-east-1
          - anyOf:
            - region: us-west-1
---